"""A `protoc` plugin that generates chattolib's Connect client stubs.

Speaks the standard plugin protocol: reads a ``CodeGeneratorRequest`` from
stdin, writes a ``CodeGeneratorResponse`` to stdout. For each proto that
declares a ``service``, it emits one ``<name>_connect.py`` defining an async
``*ServiceClient(ConnectClient)`` and a sync ``*ServiceClientSync
(ConnectClientSync)`` — both delegating to the shared runtime in
``chattolib._connect``.

Installed as the console script ``protoc-gen-chattolib`` so ``protoc`` finds
it on PATH and it is invoked with ``--chattolib_out=<dir>``.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from typing import Any

_CODEGEN_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_codegen")


def _load_codegen_module(name: str) -> Any:
    """Load a vendored codegen descriptor module directly from its file path.

    The descriptors live under ``chattolib._codegen``, but importing them through
    the ``chattolib`` package would execute ``chattolib/__init__.py`` (which
    eagerly imports the client) — undesirable for a standalone ``protoc`` plugin
    process. Loading by file path avoids that.
    """
    path = os.path.join(_CODEGEN_DIR, f"{name}.py")
    spec = importlib.util.spec_from_file_location(f"_chattolib_codegen_{name}", path)
    assert spec is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _load_descriptors() -> tuple[Any, Any]:
    return (
        _load_codegen_module("protoc_gen_request_pb2"),
        _load_codegen_module("protoc_gen_response_pb2"),
    )


_g, _r = _load_descriptors()
g: Any = _g
r: Any = _r

_HEADER = "# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!\n"


def _method_name(m: Any) -> str:
    """snake_case the RPC name, matching Python method naming."""
    out = []
    for i, ch in enumerate(m.name):
        if ch.isupper() and i:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def _service_preamble(fd: Any) -> str:
    """The shared header + imports for a generated module (emitted once)."""
    pb2_module = fd.name[: -len(".proto")].replace("/", ".") + "_pb2"
    return "\n".join(
        [
            _HEADER,
            f"# source: {fd.name}",
            "",
            f"import {pb2_module} as _pb2",
            "from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo",
            "",
            "",
        ]
    )


def _service_body(fd: Any, svc: Any) -> str:
    """Render one service's async + sync client classes (no preamble)."""
    pkg = fd.package
    base = f"{pkg}.{svc.name}" if pkg else svc.name
    lines: list[str] = [f"class {svc.name}Client(ConnectClient):"]
    for m in svc.method:
        mn = _method_name(m)
        in_name = m.input_type.lstrip(".").split(".")[-1]
        out_name = m.output_type.lstrip(".").split(".")[-1]
        lines += [
            f"    async def {mn}(self, request: _pb2.{in_name}, *,"
            f" headers: dict[str, str] | None = None) -> _pb2.{out_name}:",
            "        return await self.execute_unary(",
            "            request=request,",
            "            method=MethodInfo(",
            f'                name="{m.name}",',
            f'                service_name="{base}",',
            f"                input=_pb2.{in_name},",
            f"                output=_pb2.{out_name},",
            "            ),",
            "            headers=headers,",
            "        )",
            "",
        ]
    lines += [f"class {svc.name}ClientSync(ConnectClientSync):", ""]
    for m in svc.method:
        mn = _method_name(m)
        in_name = m.input_type.lstrip(".").split(".")[-1]
        out_name = m.output_type.lstrip(".").split(".")[-1]
        lines += [
            f"    def {mn}(self, request: _pb2.{in_name}, *,"
            f" headers: dict[str, str] | None = None) -> _pb2.{out_name}:",
            "        return self.execute_unary(",
            "            request=request,",
            "            method=MethodInfo(",
            f'                name="{m.name}",',
            f'                service_name="{base}",',
            f"                input=_pb2.{in_name},",
            f"                output=_pb2.{out_name},",
            "            ),",
            "            headers=headers,",
            "        )",
            "",
        ]
    return "\n".join(lines)


def generate(request: g.CodeGeneratorRequest) -> r.CodeGeneratorResponse:
    resp = r.CodeGeneratorResponse()
    # Tell protoc (>= the version that checks this) we can handle proto3
    # `optional` fields. Without this bit, recent protoc refuses to run the
    # plugin on any proto3 file that declares an optional field.
    resp.supported_features = r.CodeGeneratorResponse.Feature.FEATURE_PROTO3_OPTIONAL
    # file_to_generate is a repeated *string* (proto file names), not a list of
    # message objects — match by string membership.
    to_generate = set(request.file_to_generate)
    for fd in request.proto_file:
        if fd.name not in to_generate:
            continue
        services = [svc for svc in fd.service if svc.method]
        if not services:
            continue
        # One file per proto, containing every service it declares (e.g.
        # notifications.proto -> NotificationServiceClient and
        # NotificationPolicyServiceClient in the same module), matching the
        # historical connectrpc layout.
        out = resp.file.add()
        out.name = fd.name.replace(".proto", "_connect.py")
        out.content = _service_preamble(fd) + "\n".join(
            _service_body(fd, svc) for svc in services
        )
    return resp


def main() -> None:
    data = sys.stdin.buffer.read()
    request = g.CodeGeneratorRequest.FromString(data)
    resp = generate(request)
    sys.stdout.buffer.write(resp.SerializeToString())


if __name__ == "__main__":
    main()
