# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/discovery/v1/server.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'chatto/discovery/v1/server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chatto.api.v1 import server_pb2 as chatto_dot_api_dot_v1_dot_server__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n chatto/discovery/v1/server.proto\x12\x13\x63hatto.discovery.v1\x1a\x1a\x63hatto/api/v1/server.proto\"\x12\n\x10GetServerRequest\"\x8b\x01\n\x11GetServerResponse\x12\x33\n\x07profile\x18\x01 \x01(\x0b\x32\".chatto.api.v1.ServerPublicProfile\x12)\n\x05login\x18\x02 \x01(\x0b\x32\x1a.chatto.api.v1.ServerLogin\x12\x16\n\x0esetup_required\x18\x03 \x01(\x08\"\x16\n\x14ListNeighborsRequest\"9\n\x15ListNeighborsResponse\x12\x0f\n\x07origins\x18\x01 \x03(\tJ\x04\x08\x02\x10\x03R\tneighbors2\xe6\x01\n\x16ServerDiscoveryService\x12_\n\tGetServer\x12%.chatto.discovery.v1.GetServerRequest\x1a&.chatto.discovery.v1.GetServerResponse\"\x03\x90\x02\x01\x12k\n\rListNeighbors\x12).chatto.discovery.v1.ListNeighborsRequest\x1a*.chatto.discovery.v1.ListNeighborsResponse\"\x03\x90\x02\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.discovery.v1.server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERDISCOVERYSERVICE'].methods_by_name['GetServer']._loaded_options = None
  _globals['_SERVERDISCOVERYSERVICE'].methods_by_name['GetServer']._serialized_options = b'\220\002\001'
  _globals['_SERVERDISCOVERYSERVICE'].methods_by_name['ListNeighbors']._loaded_options = None
  _globals['_SERVERDISCOVERYSERVICE'].methods_by_name['ListNeighbors']._serialized_options = b'\220\002\001'
  _globals['_GETSERVERREQUEST']._serialized_start=85
  _globals['_GETSERVERREQUEST']._serialized_end=103
  _globals['_GETSERVERRESPONSE']._serialized_start=106
  _globals['_GETSERVERRESPONSE']._serialized_end=245
  _globals['_LISTNEIGHBORSREQUEST']._serialized_start=247
  _globals['_LISTNEIGHBORSREQUEST']._serialized_end=269
  _globals['_LISTNEIGHBORSRESPONSE']._serialized_start=271
  _globals['_LISTNEIGHBORSRESPONSE']._serialized_end=328
  _globals['_SERVERDISCOVERYSERVICE']._serialized_start=331
  _globals['_SERVERDISCOVERYSERVICE']._serialized_end=561
# @@protoc_insertion_point(module_scope)
