# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/account.proto

import chatto.api.v1.account_pb2 as _pb2
import chatto.api.v1.external_identities_pb2 as _pb2_external_identities
import chatto.api.v1.presence_pb2 as _pb2_presence
import chatto.api.v1.user_status_pb2 as _pb2_user_status
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class MyAccountServiceClient(ConnectClient):
    async def update_profile(self, request: _pb2.UpdateProfileRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateProfileResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProfile",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UpdateProfileRequest,
                output=_pb2.UpdateProfileResponse,
            ),
            headers=headers,
        )

    async def upload_avatar(self, request: _pb2.UploadAvatarRequest, *, headers: dict[str, str] | None = None) -> _pb2.UploadAvatarResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadAvatar",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UploadAvatarRequest,
                output=_pb2.UploadAvatarResponse,
            ),
            headers=headers,
        )

    async def delete_avatar(self, request: _pb2.DeleteAvatarRequest, *, headers: dict[str, str] | None = None) -> _pb2.DeleteAvatarResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAvatar",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.DeleteAvatarRequest,
                output=_pb2.DeleteAvatarResponse,
            ),
            headers=headers,
        )

    async def update_password(self, request: _pb2.UpdatePasswordRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdatePasswordResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePassword",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UpdatePasswordRequest,
                output=_pb2.UpdatePasswordResponse,
            ),
            headers=headers,
        )

    async def update_settings(self, request: _pb2.UpdateSettingsRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateSettingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSettings",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UpdateSettingsRequest,
                output=_pb2.UpdateSettingsResponse,
            ),
            headers=headers,
        )

    async def list_external_identities(self, request: _pb2_external_identities.ListExternalIdentitiesRequest, *, headers: dict[str, str] | None = None) -> _pb2_external_identities.ListExternalIdentitiesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListExternalIdentities",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_external_identities.ListExternalIdentitiesRequest,
                output=_pb2_external_identities.ListExternalIdentitiesResponse,
            ),
            headers=headers,
        )

    async def start_external_identity_link(self, request: _pb2_external_identities.StartExternalIdentityLinkRequest, *, headers: dict[str, str] | None = None) -> _pb2_external_identities.StartExternalIdentityLinkResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartExternalIdentityLink",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_external_identities.StartExternalIdentityLinkRequest,
                output=_pb2_external_identities.StartExternalIdentityLinkResponse,
            ),
            headers=headers,
        )

    async def disconnect_external_identity(self, request: _pb2_external_identities.DisconnectExternalIdentityRequest, *, headers: dict[str, str] | None = None) -> _pb2_external_identities.DisconnectExternalIdentityResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DisconnectExternalIdentity",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_external_identities.DisconnectExternalIdentityRequest,
                output=_pb2_external_identities.DisconnectExternalIdentityResponse,
            ),
            headers=headers,
        )

    async def update_presence(self, request: _pb2_presence.UpdatePresenceRequest, *, headers: dict[str, str] | None = None) -> _pb2_presence.UpdatePresenceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePresence",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_presence.UpdatePresenceRequest,
                output=_pb2_presence.UpdatePresenceResponse,
            ),
            headers=headers,
        )

    async def update_custom_status(self, request: _pb2_user_status.UpdateCustomStatusRequest, *, headers: dict[str, str] | None = None) -> _pb2_user_status.UpdateCustomStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateCustomStatus",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_user_status.UpdateCustomStatusRequest,
                output=_pb2_user_status.UpdateCustomStatusResponse,
            ),
            headers=headers,
        )

    async def delete_custom_status(self, request: _pb2_user_status.DeleteCustomStatusRequest, *, headers: dict[str, str] | None = None) -> _pb2_user_status.DeleteCustomStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteCustomStatus",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_user_status.DeleteCustomStatusRequest,
                output=_pb2_user_status.DeleteCustomStatusResponse,
            ),
            headers=headers,
        )

    async def request_account_deletion(self, request: _pb2.RequestAccountDeletionRequest, *, headers: dict[str, str] | None = None) -> _pb2.RequestAccountDeletionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RequestAccountDeletion",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.RequestAccountDeletionRequest,
                output=_pb2.RequestAccountDeletionResponse,
            ),
            headers=headers,
        )

    async def delete_my_account(self, request: _pb2.DeleteMyAccountRequest, *, headers: dict[str, str] | None = None) -> _pb2.DeleteMyAccountResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteMyAccount",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.DeleteMyAccountRequest,
                output=_pb2.DeleteMyAccountResponse,
            ),
            headers=headers,
        )

class MyAccountServiceClientSync(ConnectClientSync):

    def update_profile(self, request: _pb2.UpdateProfileRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateProfileResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProfile",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UpdateProfileRequest,
                output=_pb2.UpdateProfileResponse,
            ),
            headers=headers,
        )

    def upload_avatar(self, request: _pb2.UploadAvatarRequest, *, headers: dict[str, str] | None = None) -> _pb2.UploadAvatarResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadAvatar",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UploadAvatarRequest,
                output=_pb2.UploadAvatarResponse,
            ),
            headers=headers,
        )

    def delete_avatar(self, request: _pb2.DeleteAvatarRequest, *, headers: dict[str, str] | None = None) -> _pb2.DeleteAvatarResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAvatar",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.DeleteAvatarRequest,
                output=_pb2.DeleteAvatarResponse,
            ),
            headers=headers,
        )

    def update_password(self, request: _pb2.UpdatePasswordRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdatePasswordResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePassword",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UpdatePasswordRequest,
                output=_pb2.UpdatePasswordResponse,
            ),
            headers=headers,
        )

    def update_settings(self, request: _pb2.UpdateSettingsRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateSettingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSettings",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.UpdateSettingsRequest,
                output=_pb2.UpdateSettingsResponse,
            ),
            headers=headers,
        )

    def list_external_identities(self, request: _pb2_external_identities.ListExternalIdentitiesRequest, *, headers: dict[str, str] | None = None) -> _pb2_external_identities.ListExternalIdentitiesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListExternalIdentities",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_external_identities.ListExternalIdentitiesRequest,
                output=_pb2_external_identities.ListExternalIdentitiesResponse,
            ),
            headers=headers,
        )

    def start_external_identity_link(self, request: _pb2_external_identities.StartExternalIdentityLinkRequest, *, headers: dict[str, str] | None = None) -> _pb2_external_identities.StartExternalIdentityLinkResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartExternalIdentityLink",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_external_identities.StartExternalIdentityLinkRequest,
                output=_pb2_external_identities.StartExternalIdentityLinkResponse,
            ),
            headers=headers,
        )

    def disconnect_external_identity(self, request: _pb2_external_identities.DisconnectExternalIdentityRequest, *, headers: dict[str, str] | None = None) -> _pb2_external_identities.DisconnectExternalIdentityResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DisconnectExternalIdentity",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_external_identities.DisconnectExternalIdentityRequest,
                output=_pb2_external_identities.DisconnectExternalIdentityResponse,
            ),
            headers=headers,
        )

    def update_presence(self, request: _pb2_presence.UpdatePresenceRequest, *, headers: dict[str, str] | None = None) -> _pb2_presence.UpdatePresenceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdatePresence",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_presence.UpdatePresenceRequest,
                output=_pb2_presence.UpdatePresenceResponse,
            ),
            headers=headers,
        )

    def update_custom_status(self, request: _pb2_user_status.UpdateCustomStatusRequest, *, headers: dict[str, str] | None = None) -> _pb2_user_status.UpdateCustomStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateCustomStatus",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_user_status.UpdateCustomStatusRequest,
                output=_pb2_user_status.UpdateCustomStatusResponse,
            ),
            headers=headers,
        )

    def delete_custom_status(self, request: _pb2_user_status.DeleteCustomStatusRequest, *, headers: dict[str, str] | None = None) -> _pb2_user_status.DeleteCustomStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteCustomStatus",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2_user_status.DeleteCustomStatusRequest,
                output=_pb2_user_status.DeleteCustomStatusResponse,
            ),
            headers=headers,
        )

    def request_account_deletion(self, request: _pb2.RequestAccountDeletionRequest, *, headers: dict[str, str] | None = None) -> _pb2.RequestAccountDeletionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RequestAccountDeletion",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.RequestAccountDeletionRequest,
                output=_pb2.RequestAccountDeletionResponse,
            ),
            headers=headers,
        )

    def delete_my_account(self, request: _pb2.DeleteMyAccountRequest, *, headers: dict[str, str] | None = None) -> _pb2.DeleteMyAccountResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteMyAccount",
                service_name="chatto.api.v1.MyAccountService",
                input=_pb2.DeleteMyAccountRequest,
                output=_pb2.DeleteMyAccountResponse,
            ),
            headers=headers,
        )
