# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/api/v1/common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'chatto/api/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63hatto/api/v1/common.proto\x12\rchatto.api.v1\x1a\x1b\x62uf/validate/validate.proto\"\x82\x01\n\x15ImageTransformOptions\x12\x19\n\x05width\x18\x01 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\x80 (\x01\x12\x1a\n\x06height\x18\x02 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\x80 (\x01\x12\x32\n\x03\x66it\x18\x03 \x01(\x0e\x32\x1b.chatto.api.v1.ImageFitModeB\x08\xbaH\x05\x82\x01\x02\x10\x01\"D\n\x0bImageUpload\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"N\n\x10ProviderMetadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\x12\x11\n\tlogin_url\x18\x04 \x01(\t*d\n\x0cImageFitMode\x12\x1e\n\x1aIMAGE_FIT_MODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16IMAGE_FIT_MODE_CONTAIN\x10\x01\x12\x18\n\x14IMAGE_FIT_MODE_COVER\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.api.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGETRANSFORMOPTIONS'].fields_by_name['width']._loaded_options = None
  _globals['_IMAGETRANSFORMOPTIONS'].fields_by_name['width']._serialized_options = b'\272H\007\032\005\030\200 (\001'
  _globals['_IMAGETRANSFORMOPTIONS'].fields_by_name['height']._loaded_options = None
  _globals['_IMAGETRANSFORMOPTIONS'].fields_by_name['height']._serialized_options = b'\272H\007\032\005\030\200 (\001'
  _globals['_IMAGETRANSFORMOPTIONS'].fields_by_name['fit']._loaded_options = None
  _globals['_IMAGETRANSFORMOPTIONS'].fields_by_name['fit']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_IMAGEFITMODE']._serialized_start=357
  _globals['_IMAGEFITMODE']._serialized_end=457
  _globals['_IMAGETRANSFORMOPTIONS']._serialized_start=75
  _globals['_IMAGETRANSFORMOPTIONS']._serialized_end=205
  _globals['_IMAGEUPLOAD']._serialized_start=207
  _globals['_IMAGEUPLOAD']._serialized_end=275
  _globals['_PROVIDERMETADATA']._serialized_start=277
  _globals['_PROVIDERMETADATA']._serialized_end=355
# @@protoc_insertion_point(module_scope)
