# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/member_directory.proto

import chatto.api.v1.member_directory_pb2 as _pb2
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class UserServiceClient(ConnectClient):
    async def list_users(self, request: _pb2.ListUsersRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="chatto.api.v1.UserService",
                input=_pb2.ListUsersRequest,
                output=_pb2.ListUsersResponse,
            ),
            headers=headers,
        )

    async def get_user(self, request: _pb2.GetUserRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="chatto.api.v1.UserService",
                input=_pb2.GetUserRequest,
                output=_pb2.GetUserResponse,
            ),
            headers=headers,
        )

    async def batch_get_users(self, request: _pb2.BatchGetUsersRequest, *, headers: dict[str, str] | None = None) -> _pb2.BatchGetUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetUsers",
                service_name="chatto.api.v1.UserService",
                input=_pb2.BatchGetUsersRequest,
                output=_pb2.BatchGetUsersResponse,
            ),
            headers=headers,
        )

class UserServiceClientSync(ConnectClientSync):

    def list_users(self, request: _pb2.ListUsersRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="chatto.api.v1.UserService",
                input=_pb2.ListUsersRequest,
                output=_pb2.ListUsersResponse,
            ),
            headers=headers,
        )

    def get_user(self, request: _pb2.GetUserRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="chatto.api.v1.UserService",
                input=_pb2.GetUserRequest,
                output=_pb2.GetUserResponse,
            ),
            headers=headers,
        )

    def batch_get_users(self, request: _pb2.BatchGetUsersRequest, *, headers: dict[str, str] | None = None) -> _pb2.BatchGetUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetUsers",
                service_name="chatto.api.v1.UserService",
                input=_pb2.BatchGetUsersRequest,
                output=_pb2.BatchGetUsersResponse,
            ),
            headers=headers,
        )
