# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: chatto/api/v1/notifications.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import chatto.api.v1.notifications_pb2 as chatto_dot_api_dot_v1_dot_notifications__pb2


class NotificationService(Protocol):
    async def get_notification_occurrence(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def batch_get_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def mark_notification_read(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_notification_occurrence(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def batch_delete_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_all_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotificationServiceASGIApplication(ConnectASGIApplication[NotificationService]):
    def __init__(self, service: NotificationService | AsyncGenerator[NotificationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.NotificationService/GetNotificationOccurrence": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchGetNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/ListNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/MarkNotificationRead": Endpoint.unary(
                    method=MethodInfo(
                        name="MarkNotificationRead",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.mark_notification_read,
                ),
                "/chatto.api.v1.NotificationService/DeleteNotificationOccurrence": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.delete_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchDeleteNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchDeleteNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.batch_delete_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/DeleteAllNotificationOccurrences": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteAllNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_all_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/GetNotificationPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNotificationPolicy",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_notification_policy,
                ),
                "/chatto.api.v1.NotificationService/UpdateNotificationPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateNotificationPolicy",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_notification_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationService"


class NotificationServiceClient(ConnectClient):
    async def get_notification_occurrence(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def mark_notification_read(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkNotificationRead",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_notification_occurrence(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_delete_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchDeleteNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_all_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAllNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPolicy",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateNotificationPolicy",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class NotificationPolicyService(Protocol):
    async def get_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def batch_get_notification_policies(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotificationPolicyServiceASGIApplication(ConnectASGIApplication[NotificationPolicyService]):
    def __init__(self, service: NotificationPolicyService | AsyncGenerator[NotificationPolicyService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/chatto.api.v1.NotificationPolicyService/GetNotificationPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_notification_policy,
                ),
                "/chatto.api.v1.NotificationPolicyService/BatchGetNotificationPolicies": Endpoint.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationPolicies",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.batch_get_notification_policies,
                ),
                "/chatto.api.v1.NotificationPolicyService/UpdateNotificationPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_notification_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationPolicyService"


class NotificationPolicyServiceClient(ConnectClient):
    async def get_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def batch_get_notification_policies(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationPolicies",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class NotificationServiceSync(Protocol):
    def get_notification_occurrence(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def batch_get_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def mark_notification_read(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_notification_occurrence(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def batch_delete_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_all_notification_occurrences(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotificationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: NotificationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.NotificationService/GetNotificationOccurrence": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchGetNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/ListNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/MarkNotificationRead": EndpointSync.unary(
                    method=MethodInfo(
                        name="MarkNotificationRead",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.mark_notification_read,
                ),
                "/chatto.api.v1.NotificationService/DeleteNotificationOccurrence": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteNotificationOccurrence",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.delete_notification_occurrence,
                ),
                "/chatto.api.v1.NotificationService/BatchDeleteNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchDeleteNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.batch_delete_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/DeleteAllNotificationOccurrences": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteAllNotificationOccurrences",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_all_notification_occurrences,
                ),
                "/chatto.api.v1.NotificationService/GetNotificationPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNotificationPolicy",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_notification_policy,
                ),
                "/chatto.api.v1.NotificationService/UpdateNotificationPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateNotificationPolicy",
                        service_name="chatto.api.v1.NotificationService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_notification_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationService"


class NotificationServiceClientSync(ConnectClientSync):
    def get_notification_occurrence(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def batch_get_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.ListNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def mark_notification_read(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkNotificationRead",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.MarkNotificationReadResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_notification_occurrence(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteNotificationOccurrence",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteNotificationOccurrenceResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def batch_delete_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchDeleteNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchDeleteNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_all_notification_occurrences(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAllNotificationOccurrences",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.DeleteAllNotificationOccurrencesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPolicy",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.GetNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateNotificationPolicy",
                service_name="chatto.api.v1.NotificationService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.UpdateNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class NotificationPolicyServiceSync(Protocol):
    def get_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def batch_get_notification_policies(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_notification_policy(self, request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest, ctx: RequestContext) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NotificationPolicyServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: NotificationPolicyServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/chatto.api.v1.NotificationPolicyService/GetNotificationPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_notification_policy,
                ),
                "/chatto.api.v1.NotificationPolicyService/BatchGetNotificationPolicies": EndpointSync.unary(
                    method=MethodInfo(
                        name="BatchGetNotificationPolicies",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.batch_get_notification_policies,
                ),
                "/chatto.api.v1.NotificationPolicyService/UpdateNotificationPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateNotificationPolicy",
                        service_name="chatto.api.v1.NotificationPolicyService",
                        input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest,
                        output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_notification_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/chatto.api.v1.NotificationPolicyService"


class NotificationPolicyServiceClientSync(ConnectClientSync):
    def get_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceGetNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def batch_get_notification_policies(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetNotificationPolicies",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.BatchGetNotificationPoliciesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_notification_policy(
        self,
        request: chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateNotificationPolicy",
                service_name="chatto.api.v1.NotificationPolicyService",
                input=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyRequest,
                output=chatto_dot_api_dot_v1_dot_notifications__pb2.NotificationPolicyServiceUpdateNotificationPolicyResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
