# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/api/v1/presence.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'chatto/api/v1/presence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63hatto/api/v1/presence.proto\x12\rchatto.api.v1\x1a\x1b\x62uf/validate/validate.proto\"U\n\x12PresencePreference\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.chatto.api.v1.PresenceStatus\x12\x10\n\x08revision\x18\x02 \x01(\t\"\x1e\n\x1cGetPresencePreferenceRequest\"V\n\x1dGetPresencePreferenceResponse\x12\x35\n\npreference\x18\x01 \x01(\x0b\x32!.chatto.api.v1.PresencePreference\"t\n\x1cSetPresencePreferenceRequest\x12\x39\n\x06status\x18\x01 \x01(\x0e\x32\x1d.chatto.api.v1.PresenceStatusB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00\x12\x19\n\x11\x65xpected_revision\x18\x02 \x01(\t\"V\n\x1dSetPresencePreferenceResponse\x12\x35\n\npreference\x18\x01 \x01(\x0b\x32!.chatto.api.v1.PresencePreference\"\x18\n\x16RefreshPresenceRequest\"P\n\x17RefreshPresenceResponse\x12\x35\n\npreference\x18\x01 \x01(\x0b\x32!.chatto.api.v1.PresencePreference\"h\n\x12SetPresenceRequest\x12;\n\x06status\x18\x01 \x01(\x0e\x32\x1d.chatto.api.v1.PresenceStatusB\x0c\xbaH\t\x82\x01\x06\x10\x01 \x00 \x04\x12\x15\n\ruser_selected\x18\x02 \x01(\x08\"D\n\x13SetPresenceResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.chatto.api.v1.PresenceStatus*\xa8\x01\n\x0ePresenceStatus\x12\x1f\n\x1bPRESENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n\x16PRESENCE_STATUS_ONLINE\x10\x01\x12\x18\n\x14PRESENCE_STATUS_AWAY\x10\x02\x12\"\n\x1ePRESENCE_STATUS_DO_NOT_DISTURB\x10\x03\x12\x1b\n\x17PRESENCE_STATUS_OFFLINE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.api.v1.presence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETPRESENCEPREFERENCEREQUEST'].fields_by_name['status']._loaded_options = None
  _globals['_SETPRESENCEPREFERENCEREQUEST'].fields_by_name['status']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_SETPRESENCEREQUEST'].fields_by_name['status']._loaded_options = None
  _globals['_SETPRESENCEREQUEST'].fields_by_name['status']._serialized_options = b'\272H\t\202\001\006\020\001 \000 \004'
  _globals['_PRESENCESTATUS']._serialized_start=774
  _globals['_PRESENCESTATUS']._serialized_end=942
  _globals['_PRESENCEPREFERENCE']._serialized_start=76
  _globals['_PRESENCEPREFERENCE']._serialized_end=161
  _globals['_GETPRESENCEPREFERENCEREQUEST']._serialized_start=163
  _globals['_GETPRESENCEPREFERENCEREQUEST']._serialized_end=193
  _globals['_GETPRESENCEPREFERENCERESPONSE']._serialized_start=195
  _globals['_GETPRESENCEPREFERENCERESPONSE']._serialized_end=281
  _globals['_SETPRESENCEPREFERENCEREQUEST']._serialized_start=283
  _globals['_SETPRESENCEPREFERENCEREQUEST']._serialized_end=399
  _globals['_SETPRESENCEPREFERENCERESPONSE']._serialized_start=401
  _globals['_SETPRESENCEPREFERENCERESPONSE']._serialized_end=487
  _globals['_REFRESHPRESENCEREQUEST']._serialized_start=489
  _globals['_REFRESHPRESENCEREQUEST']._serialized_end=513
  _globals['_REFRESHPRESENCERESPONSE']._serialized_start=515
  _globals['_REFRESHPRESENCERESPONSE']._serialized_end=595
  _globals['_SETPRESENCEREQUEST']._serialized_start=597
  _globals['_SETPRESENCEREQUEST']._serialized_end=701
  _globals['_SETPRESENCERESPONSE']._serialized_start=703
  _globals['_SETPRESENCERESPONSE']._serialized_end=771
# @@protoc_insertion_point(module_scope)
