# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/push_notifications.proto

import chatto.api.v1.push_notifications_pb2 as _pb2
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class PushNotificationServiceClient(ConnectClient):
    async def subscribe(self, request: _pb2.SubscribePushRequest, *, headers: dict[str, str] | None = None) -> _pb2.SubscribePushResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Subscribe",
                service_name="chatto.api.v1.PushNotificationService",
                input=_pb2.SubscribePushRequest,
                output=_pb2.SubscribePushResponse,
            ),
            headers=headers,
        )

    async def unsubscribe(self, request: _pb2.UnsubscribePushRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnsubscribePushResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Unsubscribe",
                service_name="chatto.api.v1.PushNotificationService",
                input=_pb2.UnsubscribePushRequest,
                output=_pb2.UnsubscribePushResponse,
            ),
            headers=headers,
        )

    async def send_test_notification(self, request: _pb2.SendTestPushNotificationRequest, *, headers: dict[str, str] | None = None) -> _pb2.SendTestPushNotificationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendTestNotification",
                service_name="chatto.api.v1.PushNotificationService",
                input=_pb2.SendTestPushNotificationRequest,
                output=_pb2.SendTestPushNotificationResponse,
            ),
            headers=headers,
        )

class PushNotificationServiceClientSync(ConnectClientSync):

    def subscribe(self, request: _pb2.SubscribePushRequest, *, headers: dict[str, str] | None = None) -> _pb2.SubscribePushResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Subscribe",
                service_name="chatto.api.v1.PushNotificationService",
                input=_pb2.SubscribePushRequest,
                output=_pb2.SubscribePushResponse,
            ),
            headers=headers,
        )

    def unsubscribe(self, request: _pb2.UnsubscribePushRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnsubscribePushResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Unsubscribe",
                service_name="chatto.api.v1.PushNotificationService",
                input=_pb2.UnsubscribePushRequest,
                output=_pb2.UnsubscribePushResponse,
            ),
            headers=headers,
        )

    def send_test_notification(self, request: _pb2.SendTestPushNotificationRequest, *, headers: dict[str, str] | None = None) -> _pb2.SendTestPushNotificationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SendTestNotification",
                service_name="chatto.api.v1.PushNotificationService",
                input=_pb2.SendTestPushNotificationRequest,
                output=_pb2.SendTestPushNotificationResponse,
            ),
            headers=headers,
        )
