# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/api/v1/push_notifications.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'chatto/api/v1/push_notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&chatto/api/v1/push_notifications.proto\x12\rchatto.api.v1\x1a\x1b\x62uf/validate/validate.proto\x1a google/protobuf/descriptor.proto\"\xe0\x01\n\x14SubscribePushRequest\x12\x1c\n\x08\x65ndpoint\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80 \x12\x1a\n\x06p256dh\x18\x02 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80\x02\x12\x18\n\x04\x61uth\x18\x03 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80\x01\x12!\n\nuser_agent\x18\x04 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x04H\x00\x88\x01\x01\x12\x1f\n\x0b\x63lient_host\x18\x05 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\xff\x01\x12!\n\rcleanup_token\x18\x06 \x01(\tB\n\xbaH\x07r\x05\x10 \x18\x80\x01\x42\r\n\x0b_user_agent\"+\n\x15SubscribePushResponse\x12\x12\n\nsubscribed\x18\x01 \x01(\x08\"6\n\x16UnsubscribePushRequest\x12\x1c\n\x08\x65ndpoint\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80 \"/\n\x17UnsubscribePushResponse\x12\x14\n\x0cunsubscribed\x18\x01 \x01(\x08\"!\n\x1fSendTestPushNotificationRequest\"0\n SendTestPushNotificationResponse\x12\x0c\n\x04sent\x18\x01 \x01(\x08\x32\xcd\x02\n\x17PushNotificationService\x12V\n\tSubscribe\x12#.chatto.api.v1.SubscribePushRequest\x1a$.chatto.api.v1.SubscribePushResponse\x12\x61\n\x0bUnsubscribe\x12%.chatto.api.v1.UnsubscribePushRequest\x1a&.chatto.api.v1.UnsubscribePushResponse\"\x03\x90\x02\x02\x12w\n\x14SendTestNotification\x12..chatto.api.v1.SendTestPushNotificationRequest\x1a/.chatto.api.v1.SendTestPushNotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.api.v1.push_notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['endpoint']._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['endpoint']._serialized_options = b'\272H\007r\005\020\001\030\200 '
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['p256dh']._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['p256dh']._serialized_options = b'\272H\007r\005\020\001\030\200\002'
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['auth']._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['auth']._serialized_options = b'\272H\007r\005\020\001\030\200\001'
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['user_agent']._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['user_agent']._serialized_options = b'\272H\005r\003\030\200\004'
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['client_host']._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['client_host']._serialized_options = b'\272H\007r\005\020\001\030\377\001'
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['cleanup_token']._loaded_options = None
  _globals['_SUBSCRIBEPUSHREQUEST'].fields_by_name['cleanup_token']._serialized_options = b'\272H\007r\005\020 \030\200\001'
  _globals['_UNSUBSCRIBEPUSHREQUEST'].fields_by_name['endpoint']._loaded_options = None
  _globals['_UNSUBSCRIBEPUSHREQUEST'].fields_by_name['endpoint']._serialized_options = b'\272H\007r\005\020\001\030\200 '
  _globals['_PUSHNOTIFICATIONSERVICE'].methods_by_name['Unsubscribe']._loaded_options = None
  _globals['_PUSHNOTIFICATIONSERVICE'].methods_by_name['Unsubscribe']._serialized_options = b'\220\002\002'
  _globals['_SUBSCRIBEPUSHREQUEST']._serialized_start=121
  _globals['_SUBSCRIBEPUSHREQUEST']._serialized_end=345
  _globals['_SUBSCRIBEPUSHRESPONSE']._serialized_start=347
  _globals['_SUBSCRIBEPUSHRESPONSE']._serialized_end=390
  _globals['_UNSUBSCRIBEPUSHREQUEST']._serialized_start=392
  _globals['_UNSUBSCRIBEPUSHREQUEST']._serialized_end=446
  _globals['_UNSUBSCRIBEPUSHRESPONSE']._serialized_start=448
  _globals['_UNSUBSCRIBEPUSHRESPONSE']._serialized_end=495
  _globals['_SENDTESTPUSHNOTIFICATIONREQUEST']._serialized_start=497
  _globals['_SENDTESTPUSHNOTIFICATIONREQUEST']._serialized_end=530
  _globals['_SENDTESTPUSHNOTIFICATIONRESPONSE']._serialized_start=532
  _globals['_SENDTESTPUSHNOTIFICATIONRESPONSE']._serialized_end=580
  _globals['_PUSHNOTIFICATIONSERVICE']._serialized_start=583
  _globals['_PUSHNOTIFICATIONSERVICE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
