# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/rooms.proto

import chatto.api.v1.rooms_pb2 as _pb2
import chatto.api.v1.member_directory_pb2 as _pb2_member_directory
import chatto.api.v1.room_timeline_pb2 as _pb2_room_timeline
import chatto.api.v1.read_state_pb2 as _pb2_read_state
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class RoomServiceClient(ConnectClient):
    async def create_room(self, request: _pb2.CreateRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.CreateRoomResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.CreateRoomRequest,
                output=_pb2.CreateRoomResponse,
            ),
            headers=headers,
        )

    async def update_room(self, request: _pb2.UpdateRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateRoomResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UpdateRoomRequest,
                output=_pb2.UpdateRoomResponse,
            ),
            headers=headers,
        )

    async def archive_room(self, request: _pb2.ArchiveRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.ArchiveRoomResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ArchiveRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ArchiveRoomRequest,
                output=_pb2.ArchiveRoomResponse,
            ),
            headers=headers,
        )

    async def unarchive_room(self, request: _pb2.UnarchiveRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnarchiveRoomResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnarchiveRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UnarchiveRoomRequest,
                output=_pb2.UnarchiveRoomResponse,
            ),
            headers=headers,
        )

    async def join_room(self, request: _pb2.JoinRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.JoinRoomResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="JoinRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.JoinRoomRequest,
                output=_pb2.JoinRoomResponse,
            ),
            headers=headers,
        )

    async def join_room_group(self, request: _pb2.JoinRoomGroupRequest, *, headers: dict[str, str] | None = None) -> _pb2.JoinRoomGroupResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="JoinRoomGroup",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.JoinRoomGroupRequest,
                output=_pb2.JoinRoomGroupResponse,
            ),
            headers=headers,
        )

    async def start_d_m(self, request: _pb2.StartDMRequest, *, headers: dict[str, str] | None = None) -> _pb2.StartDMResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartDM",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.StartDMRequest,
                output=_pb2.StartDMResponse,
            ),
            headers=headers,
        )

    async def leave_room(self, request: _pb2.LeaveRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.LeaveRoomResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LeaveRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.LeaveRoomRequest,
                output=_pb2.LeaveRoomResponse,
            ),
            headers=headers,
        )

    async def list_members(self, request: _pb2_member_directory.ListRoomMembersRequest, *, headers: dict[str, str] | None = None) -> _pb2_member_directory.ListRoomMembersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMembers",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_member_directory.ListRoomMembersRequest,
                output=_pb2_member_directory.ListRoomMembersResponse,
            ),
            headers=headers,
        )

    async def get_member(self, request: _pb2_member_directory.GetRoomMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2_member_directory.GetRoomMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_member_directory.GetRoomMemberRequest,
                output=_pb2_member_directory.GetRoomMemberResponse,
            ),
            headers=headers,
        )

    async def batch_get_members(self, request: _pb2_member_directory.BatchGetRoomMembersRequest, *, headers: dict[str, str] | None = None) -> _pb2_member_directory.BatchGetRoomMembersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetMembers",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_member_directory.BatchGetRoomMembersRequest,
                output=_pb2_member_directory.BatchGetRoomMembersResponse,
            ),
            headers=headers,
        )

    async def add_member(self, request: _pb2.AddMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.AddMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.AddMemberRequest,
                output=_pb2.AddMemberResponse,
            ),
            headers=headers,
        )

    async def remove_member(self, request: _pb2.RemoveMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.RemoveMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.RemoveMemberRequest,
                output=_pb2.RemoveMemberResponse,
            ),
            headers=headers,
        )

    async def list_bans(self, request: _pb2.ListBansRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListBansResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBans",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ListBansRequest,
                output=_pb2.ListBansResponse,
            ),
            headers=headers,
        )

    async def list_room_attachments(self, request: _pb2.ListRoomAttachmentsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListRoomAttachmentsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRoomAttachments",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ListRoomAttachmentsRequest,
                output=_pb2.ListRoomAttachmentsResponse,
            ),
            headers=headers,
        )

    async def list_pinned_messages(self, request: _pb2.ListPinnedMessagesRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListPinnedMessagesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPinnedMessages",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ListPinnedMessagesRequest,
                output=_pb2.ListPinnedMessagesResponse,
            ),
            headers=headers,
        )

    async def create_pinned_message(self, request: _pb2.CreatePinnedMessageRequest, *, headers: dict[str, str] | None = None) -> _pb2.CreatePinnedMessageResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePinnedMessage",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.CreatePinnedMessageRequest,
                output=_pb2.CreatePinnedMessageResponse,
            ),
            headers=headers,
        )

    async def delete_pinned_message(self, request: _pb2.DeletePinnedMessageRequest, *, headers: dict[str, str] | None = None) -> _pb2.DeletePinnedMessageResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePinnedMessage",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.DeletePinnedMessageRequest,
                output=_pb2.DeletePinnedMessageResponse,
            ),
            headers=headers,
        )

    async def update_typing_indicator(self, request: _pb2.UpdateTypingIndicatorRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateTypingIndicatorResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateTypingIndicator",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UpdateTypingIndicatorRequest,
                output=_pb2.UpdateTypingIndicatorResponse,
            ),
            headers=headers,
        )

    async def get_room_events(self, request: _pb2_room_timeline.GetRoomEventsRequest, *, headers: dict[str, str] | None = None) -> _pb2_room_timeline.GetRoomEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoomEvents",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_room_timeline.GetRoomEventsRequest,
                output=_pb2_room_timeline.GetRoomEventsResponse,
            ),
            headers=headers,
        )

    async def get_room_events_around(self, request: _pb2_room_timeline.GetRoomEventsAroundRequest, *, headers: dict[str, str] | None = None) -> _pb2_room_timeline.GetRoomEventsAroundResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoomEventsAround",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_room_timeline.GetRoomEventsAroundRequest,
                output=_pb2_room_timeline.GetRoomEventsAroundResponse,
            ),
            headers=headers,
        )

    async def mark_room_as_read(self, request: _pb2_read_state.MarkRoomAsReadRequest, *, headers: dict[str, str] | None = None) -> _pb2_read_state.MarkRoomAsReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkRoomAsRead",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_read_state.MarkRoomAsReadRequest,
                output=_pb2_read_state.MarkRoomAsReadResponse,
            ),
            headers=headers,
        )

    async def ban_member(self, request: _pb2.BanMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.BanMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BanMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.BanMemberRequest,
                output=_pb2.BanMemberResponse,
            ),
            headers=headers,
        )

    async def unban_member(self, request: _pb2.UnbanMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnbanMemberResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnbanMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UnbanMemberRequest,
                output=_pb2.UnbanMemberResponse,
            ),
            headers=headers,
        )

class RoomServiceClientSync(ConnectClientSync):

    def create_room(self, request: _pb2.CreateRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.CreateRoomResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.CreateRoomRequest,
                output=_pb2.CreateRoomResponse,
            ),
            headers=headers,
        )

    def update_room(self, request: _pb2.UpdateRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateRoomResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UpdateRoomRequest,
                output=_pb2.UpdateRoomResponse,
            ),
            headers=headers,
        )

    def archive_room(self, request: _pb2.ArchiveRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.ArchiveRoomResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ArchiveRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ArchiveRoomRequest,
                output=_pb2.ArchiveRoomResponse,
            ),
            headers=headers,
        )

    def unarchive_room(self, request: _pb2.UnarchiveRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnarchiveRoomResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnarchiveRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UnarchiveRoomRequest,
                output=_pb2.UnarchiveRoomResponse,
            ),
            headers=headers,
        )

    def join_room(self, request: _pb2.JoinRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.JoinRoomResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="JoinRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.JoinRoomRequest,
                output=_pb2.JoinRoomResponse,
            ),
            headers=headers,
        )

    def join_room_group(self, request: _pb2.JoinRoomGroupRequest, *, headers: dict[str, str] | None = None) -> _pb2.JoinRoomGroupResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="JoinRoomGroup",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.JoinRoomGroupRequest,
                output=_pb2.JoinRoomGroupResponse,
            ),
            headers=headers,
        )

    def start_d_m(self, request: _pb2.StartDMRequest, *, headers: dict[str, str] | None = None) -> _pb2.StartDMResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartDM",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.StartDMRequest,
                output=_pb2.StartDMResponse,
            ),
            headers=headers,
        )

    def leave_room(self, request: _pb2.LeaveRoomRequest, *, headers: dict[str, str] | None = None) -> _pb2.LeaveRoomResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LeaveRoom",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.LeaveRoomRequest,
                output=_pb2.LeaveRoomResponse,
            ),
            headers=headers,
        )

    def list_members(self, request: _pb2_member_directory.ListRoomMembersRequest, *, headers: dict[str, str] | None = None) -> _pb2_member_directory.ListRoomMembersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListMembers",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_member_directory.ListRoomMembersRequest,
                output=_pb2_member_directory.ListRoomMembersResponse,
            ),
            headers=headers,
        )

    def get_member(self, request: _pb2_member_directory.GetRoomMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2_member_directory.GetRoomMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_member_directory.GetRoomMemberRequest,
                output=_pb2_member_directory.GetRoomMemberResponse,
            ),
            headers=headers,
        )

    def batch_get_members(self, request: _pb2_member_directory.BatchGetRoomMembersRequest, *, headers: dict[str, str] | None = None) -> _pb2_member_directory.BatchGetRoomMembersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetMembers",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_member_directory.BatchGetRoomMembersRequest,
                output=_pb2_member_directory.BatchGetRoomMembersResponse,
            ),
            headers=headers,
        )

    def add_member(self, request: _pb2.AddMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.AddMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AddMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.AddMemberRequest,
                output=_pb2.AddMemberResponse,
            ),
            headers=headers,
        )

    def remove_member(self, request: _pb2.RemoveMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.RemoveMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RemoveMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.RemoveMemberRequest,
                output=_pb2.RemoveMemberResponse,
            ),
            headers=headers,
        )

    def list_bans(self, request: _pb2.ListBansRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListBansResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBans",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ListBansRequest,
                output=_pb2.ListBansResponse,
            ),
            headers=headers,
        )

    def list_room_attachments(self, request: _pb2.ListRoomAttachmentsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListRoomAttachmentsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRoomAttachments",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ListRoomAttachmentsRequest,
                output=_pb2.ListRoomAttachmentsResponse,
            ),
            headers=headers,
        )

    def list_pinned_messages(self, request: _pb2.ListPinnedMessagesRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListPinnedMessagesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPinnedMessages",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.ListPinnedMessagesRequest,
                output=_pb2.ListPinnedMessagesResponse,
            ),
            headers=headers,
        )

    def create_pinned_message(self, request: _pb2.CreatePinnedMessageRequest, *, headers: dict[str, str] | None = None) -> _pb2.CreatePinnedMessageResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePinnedMessage",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.CreatePinnedMessageRequest,
                output=_pb2.CreatePinnedMessageResponse,
            ),
            headers=headers,
        )

    def delete_pinned_message(self, request: _pb2.DeletePinnedMessageRequest, *, headers: dict[str, str] | None = None) -> _pb2.DeletePinnedMessageResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePinnedMessage",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.DeletePinnedMessageRequest,
                output=_pb2.DeletePinnedMessageResponse,
            ),
            headers=headers,
        )

    def update_typing_indicator(self, request: _pb2.UpdateTypingIndicatorRequest, *, headers: dict[str, str] | None = None) -> _pb2.UpdateTypingIndicatorResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateTypingIndicator",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UpdateTypingIndicatorRequest,
                output=_pb2.UpdateTypingIndicatorResponse,
            ),
            headers=headers,
        )

    def get_room_events(self, request: _pb2_room_timeline.GetRoomEventsRequest, *, headers: dict[str, str] | None = None) -> _pb2_room_timeline.GetRoomEventsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoomEvents",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_room_timeline.GetRoomEventsRequest,
                output=_pb2_room_timeline.GetRoomEventsResponse,
            ),
            headers=headers,
        )

    def get_room_events_around(self, request: _pb2_room_timeline.GetRoomEventsAroundRequest, *, headers: dict[str, str] | None = None) -> _pb2_room_timeline.GetRoomEventsAroundResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRoomEventsAround",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_room_timeline.GetRoomEventsAroundRequest,
                output=_pb2_room_timeline.GetRoomEventsAroundResponse,
            ),
            headers=headers,
        )

    def mark_room_as_read(self, request: _pb2_read_state.MarkRoomAsReadRequest, *, headers: dict[str, str] | None = None) -> _pb2_read_state.MarkRoomAsReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkRoomAsRead",
                service_name="chatto.api.v1.RoomService",
                input=_pb2_read_state.MarkRoomAsReadRequest,
                output=_pb2_read_state.MarkRoomAsReadResponse,
            ),
            headers=headers,
        )

    def ban_member(self, request: _pb2.BanMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.BanMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BanMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.BanMemberRequest,
                output=_pb2.BanMemberResponse,
            ),
            headers=headers,
        )

    def unban_member(self, request: _pb2.UnbanMemberRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnbanMemberResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnbanMember",
                service_name="chatto.api.v1.RoomService",
                input=_pb2.UnbanMemberRequest,
                output=_pb2.UnbanMemberResponse,
            ),
            headers=headers,
        )
