# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/api/v1/server.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'chatto/api/v1/server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chatto.api.v1 import common_pb2 as chatto_dot_api_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63hatto/api/v1/server.proto\x12\rchatto.api.v1\x1a\x1a\x63hatto/api/v1/common.proto\"\xdc\x01\n\x13ServerPublicProfile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x15\n\x08logo_url\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nbanner_url\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0fwelcome_message\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x06 \x01(\tH\x03\x88\x01\x01\x42\x0b\n\t_logo_urlB\r\n\x0b_banner_urlB\x12\n\x10_welcome_messageB\x0e\n\x0c_description\"}\n\x0bServerLogin\x12#\n\x1b\x64irect_registration_enabled\x18\x01 \x01(\x08\x12\x32\n\tproviders\x18\x02 \x03(\x0b\x32\x1f.chatto.api.v1.ProviderMetadata\x12\x15\n\rauthorize_url\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.api.v1.server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERPUBLICPROFILE']._serialized_start=74
  _globals['_SERVERPUBLICPROFILE']._serialized_end=294
  _globals['_SERVERLOGIN']._serialized_start=296
  _globals['_SERVERLOGIN']._serialized_end=421
# @@protoc_insertion_point(module_scope)
