# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/threads.proto

import chatto.api.v1.threads_pb2 as _pb2
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class ThreadServiceClient(ConnectClient):
    async def list_followed_threads(self, request: _pb2.ListFollowedThreadsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListFollowedThreadsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListFollowedThreads",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.ListFollowedThreadsRequest,
                output=_pb2.ListFollowedThreadsResponse,
            ),
            headers=headers,
        )

    async def follow_thread(self, request: _pb2.FollowThreadRequest, *, headers: dict[str, str] | None = None) -> _pb2.FollowThreadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.FollowThreadRequest,
                output=_pb2.FollowThreadResponse,
            ),
            headers=headers,
        )

    async def unfollow_thread(self, request: _pb2.UnfollowThreadRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnfollowThreadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnfollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.UnfollowThreadRequest,
                output=_pb2.UnfollowThreadResponse,
            ),
            headers=headers,
        )

    async def get_thread_events(self, request: _pb2.GetThreadEventsRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetThreadEventsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEvents",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.GetThreadEventsRequest,
                output=_pb2.GetThreadEventsResponse,
            ),
            headers=headers,
        )

    async def get_thread_events_around(self, request: _pb2.GetThreadEventsAroundRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetThreadEventsAroundResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEventsAround",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.GetThreadEventsAroundRequest,
                output=_pb2.GetThreadEventsAroundResponse,
            ),
            headers=headers,
        )

    async def mark_thread_as_read(self, request: _pb2.MarkThreadAsReadRequest, *, headers: dict[str, str] | None = None) -> _pb2.MarkThreadAsReadResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkThreadAsRead",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.MarkThreadAsReadRequest,
                output=_pb2.MarkThreadAsReadResponse,
            ),
            headers=headers,
        )

class ThreadServiceClientSync(ConnectClientSync):

    def list_followed_threads(self, request: _pb2.ListFollowedThreadsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListFollowedThreadsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListFollowedThreads",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.ListFollowedThreadsRequest,
                output=_pb2.ListFollowedThreadsResponse,
            ),
            headers=headers,
        )

    def follow_thread(self, request: _pb2.FollowThreadRequest, *, headers: dict[str, str] | None = None) -> _pb2.FollowThreadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.FollowThreadRequest,
                output=_pb2.FollowThreadResponse,
            ),
            headers=headers,
        )

    def unfollow_thread(self, request: _pb2.UnfollowThreadRequest, *, headers: dict[str, str] | None = None) -> _pb2.UnfollowThreadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnfollowThread",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.UnfollowThreadRequest,
                output=_pb2.UnfollowThreadResponse,
            ),
            headers=headers,
        )

    def get_thread_events(self, request: _pb2.GetThreadEventsRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetThreadEventsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEvents",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.GetThreadEventsRequest,
                output=_pb2.GetThreadEventsResponse,
            ),
            headers=headers,
        )

    def get_thread_events_around(self, request: _pb2.GetThreadEventsAroundRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetThreadEventsAroundResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetThreadEventsAround",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.GetThreadEventsAroundRequest,
                output=_pb2.GetThreadEventsAroundResponse,
            ),
            headers=headers,
        )

    def mark_thread_as_read(self, request: _pb2.MarkThreadAsReadRequest, *, headers: dict[str, str] | None = None) -> _pb2.MarkThreadAsReadResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MarkThreadAsRead",
                service_name="chatto.api.v1.ThreadService",
                input=_pb2.MarkThreadAsReadRequest,
                output=_pb2.MarkThreadAsReadResponse,
            ),
            headers=headers,
        )
