# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/user_service.proto

import chatto.api.v1.user_service_pb2 as chatto_api_v1_user_service_pb2
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class UserServiceClient(ConnectClient):
    async def list_users(self, request: chatto_api_v1_user_service_pb2.ListUsersRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.ListUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.ListUsersRequest,
                output=chatto_api_v1_user_service_pb2.ListUsersResponse,
            ),
            headers=headers,
        )

    async def get_user(self, request: chatto_api_v1_user_service_pb2.GetUserRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.GetUserResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.GetUserRequest,
                output=chatto_api_v1_user_service_pb2.GetUserResponse,
            ),
            headers=headers,
        )

    async def batch_get_users(self, request: chatto_api_v1_user_service_pb2.BatchGetUsersRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.BatchGetUsersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetUsers",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.BatchGetUsersRequest,
                output=chatto_api_v1_user_service_pb2.BatchGetUsersResponse,
            ),
            headers=headers,
        )

    async def update_user_profile(self, request: chatto_api_v1_user_service_pb2.UpdateUserProfileRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.UpdateUserProfileResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateUserProfile",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.UpdateUserProfileRequest,
                output=chatto_api_v1_user_service_pb2.UpdateUserProfileResponse,
            ),
            headers=headers,
        )

    async def upload_avatar(self, request: chatto_api_v1_user_service_pb2.UploadAvatarRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.UploadAvatarResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadAvatar",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.UploadAvatarRequest,
                output=chatto_api_v1_user_service_pb2.UploadAvatarResponse,
            ),
            headers=headers,
        )

    async def delete_avatar(self, request: chatto_api_v1_user_service_pb2.DeleteAvatarRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.DeleteAvatarResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAvatar",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.DeleteAvatarRequest,
                output=chatto_api_v1_user_service_pb2.DeleteAvatarResponse,
            ),
            headers=headers,
        )

class UserServiceClientSync(ConnectClientSync):

    def list_users(self, request: chatto_api_v1_user_service_pb2.ListUsersRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.ListUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListUsers",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.ListUsersRequest,
                output=chatto_api_v1_user_service_pb2.ListUsersResponse,
            ),
            headers=headers,
        )

    def get_user(self, request: chatto_api_v1_user_service_pb2.GetUserRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.GetUserResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.GetUserRequest,
                output=chatto_api_v1_user_service_pb2.GetUserResponse,
            ),
            headers=headers,
        )

    def batch_get_users(self, request: chatto_api_v1_user_service_pb2.BatchGetUsersRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.BatchGetUsersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetUsers",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.BatchGetUsersRequest,
                output=chatto_api_v1_user_service_pb2.BatchGetUsersResponse,
            ),
            headers=headers,
        )

    def update_user_profile(self, request: chatto_api_v1_user_service_pb2.UpdateUserProfileRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.UpdateUserProfileResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateUserProfile",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.UpdateUserProfileRequest,
                output=chatto_api_v1_user_service_pb2.UpdateUserProfileResponse,
            ),
            headers=headers,
        )

    def upload_avatar(self, request: chatto_api_v1_user_service_pb2.UploadAvatarRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.UploadAvatarResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UploadAvatar",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.UploadAvatarRequest,
                output=chatto_api_v1_user_service_pb2.UploadAvatarResponse,
            ),
            headers=headers,
        )

    def delete_avatar(self, request: chatto_api_v1_user_service_pb2.DeleteAvatarRequest, *, headers: dict[str, str] | None = None) -> chatto_api_v1_user_service_pb2.DeleteAvatarResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAvatar",
                service_name="chatto.api.v1.UserService",
                input=chatto_api_v1_user_service_pb2.DeleteAvatarRequest,
                output=chatto_api_v1_user_service_pb2.DeleteAvatarResponse,
            ),
            headers=headers,
        )
