# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/api/v1/users.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'chatto/api/v1/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chatto.api.v1 import presence_pb2 as chatto_dot_api_dot_v1_dot_presence__pb2
from chatto.api.v1 import user_status_pb2 as chatto_dot_api_dot_v1_dot_user__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63hatto/api/v1/users.proto\x12\rchatto.api.v1\x1a\x1c\x63hatto/api/v1/presence.proto\x1a\x1f\x63hatto/api/v1/user_status.proto\"\xe0\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\x08\x12\x17\n\navatar_url\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x36\n\x0fpresence_status\x18\x06 \x01(\x0e\x32\x1d.chatto.api.v1.PresenceStatus\x12\x36\n\rcustom_status\x18\x07 \x01(\x0b\x32\x1f.chatto.api.v1.CustomUserStatusB\r\n\x0b_avatar_urlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.api.v1.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=108
  _globals['_USER']._serialized_end=332
# @@protoc_insertion_point(module_scope)
