# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatto/api/v1/user_status.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'chatto/api/v1/user_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63hatto/api/v1/user_status.proto\x12\rchatto.api.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n\x10\x43ustomUserStatus\x12\x18\n\x05\x65moji\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x10\x12\x17\n\x04text\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x64\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"h\n\x19UpdateCustomStatusRequest\x12\r\n\x05\x65moji\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"M\n\x1aUpdateCustomStatusResponse\x12/\n\x06status\x18\x01 \x01(\x0b\x32\x1f.chatto.api.v1.CustomUserStatus\"\x1b\n\x19\x44\x65leteCustomStatusRequest\"M\n\x1a\x44\x65leteCustomStatusResponse\x12/\n\x06status\x18\x01 \x01(\x0b\x32\x1f.chatto.api.v1.CustomUserStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatto.api.v1.user_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMUSERSTATUS'].fields_by_name['emoji']._loaded_options = None
  _globals['_CUSTOMUSERSTATUS'].fields_by_name['emoji']._serialized_options = b'\272H\006r\004\020\001\030\020'
  _globals['_CUSTOMUSERSTATUS'].fields_by_name['text']._loaded_options = None
  _globals['_CUSTOMUSERSTATUS'].fields_by_name['text']._serialized_options = b'\272H\006r\004\020\001\030d'
  _globals['_CUSTOMUSERSTATUS']._serialized_start=112
  _globals['_CUSTOMUSERSTATUS']._serialized_end=229
  _globals['_UPDATECUSTOMSTATUSREQUEST']._serialized_start=231
  _globals['_UPDATECUSTOMSTATUSREQUEST']._serialized_end=335
  _globals['_UPDATECUSTOMSTATUSRESPONSE']._serialized_start=337
  _globals['_UPDATECUSTOMSTATUSRESPONSE']._serialized_end=414
  _globals['_DELETECUSTOMSTATUSREQUEST']._serialized_start=416
  _globals['_DELETECUSTOMSTATUSREQUEST']._serialized_end=443
  _globals['_DELETECUSTOMSTATUSRESPONSE']._serialized_start=445
  _globals['_DELETECUSTOMSTATUSRESPONSE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
