# Generated by chattolib's protoc plugin (protoc-gen-chattolib). DO NOT EDIT!

# source: chatto/api/v1/voice_calls.proto

import chatto.api.v1.voice_calls_pb2 as _pb2
from chattolib._connect import ConnectClient, ConnectClientSync, MethodInfo

class VoiceCallServiceClient(ConnectClient):
    async def list_active_calls(self, request: _pb2.ListActiveCallsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListActiveCallsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListActiveCalls",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.ListActiveCallsRequest,
                output=_pb2.ListActiveCallsResponse,
            ),
            headers=headers,
        )

    async def get_active_call(self, request: _pb2.GetActiveCallRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetActiveCallResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetActiveCall",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.GetActiveCallRequest,
                output=_pb2.GetActiveCallResponse,
            ),
            headers=headers,
        )

    async def batch_get_active_calls(self, request: _pb2.BatchGetActiveCallsRequest, *, headers: dict[str, str] | None = None) -> _pb2.BatchGetActiveCallsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetActiveCalls",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.BatchGetActiveCallsRequest,
                output=_pb2.BatchGetActiveCallsResponse,
            ),
            headers=headers,
        )

    async def list_call_participants(self, request: _pb2.ListCallParticipantsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListCallParticipantsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCallParticipants",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.ListCallParticipantsRequest,
                output=_pb2.ListCallParticipantsResponse,
            ),
            headers=headers,
        )

    async def join_call(self, request: _pb2.JoinCallRequest, *, headers: dict[str, str] | None = None) -> _pb2.JoinCallResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="JoinCall",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.JoinCallRequest,
                output=_pb2.JoinCallResponse,
            ),
            headers=headers,
        )

    async def get_call_token(self, request: _pb2.GetCallTokenRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetCallTokenResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCallToken",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.GetCallTokenRequest,
                output=_pb2.GetCallTokenResponse,
            ),
            headers=headers,
        )

    async def create_call_media_publisher_token(self, request: _pb2.CreateCallMediaPublisherTokenRequest, *, headers: dict[str, str] | None = None) -> _pb2.CreateCallMediaPublisherTokenResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateCallMediaPublisherToken",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.CreateCallMediaPublisherTokenRequest,
                output=_pb2.CreateCallMediaPublisherTokenResponse,
            ),
            headers=headers,
        )

    async def leave_call(self, request: _pb2.LeaveCallRequest, *, headers: dict[str, str] | None = None) -> _pb2.LeaveCallResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LeaveCall",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.LeaveCallRequest,
                output=_pb2.LeaveCallResponse,
            ),
            headers=headers,
        )

class VoiceCallServiceClientSync(ConnectClientSync):

    def list_active_calls(self, request: _pb2.ListActiveCallsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListActiveCallsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListActiveCalls",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.ListActiveCallsRequest,
                output=_pb2.ListActiveCallsResponse,
            ),
            headers=headers,
        )

    def get_active_call(self, request: _pb2.GetActiveCallRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetActiveCallResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetActiveCall",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.GetActiveCallRequest,
                output=_pb2.GetActiveCallResponse,
            ),
            headers=headers,
        )

    def batch_get_active_calls(self, request: _pb2.BatchGetActiveCallsRequest, *, headers: dict[str, str] | None = None) -> _pb2.BatchGetActiveCallsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="BatchGetActiveCalls",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.BatchGetActiveCallsRequest,
                output=_pb2.BatchGetActiveCallsResponse,
            ),
            headers=headers,
        )

    def list_call_participants(self, request: _pb2.ListCallParticipantsRequest, *, headers: dict[str, str] | None = None) -> _pb2.ListCallParticipantsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCallParticipants",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.ListCallParticipantsRequest,
                output=_pb2.ListCallParticipantsResponse,
            ),
            headers=headers,
        )

    def join_call(self, request: _pb2.JoinCallRequest, *, headers: dict[str, str] | None = None) -> _pb2.JoinCallResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="JoinCall",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.JoinCallRequest,
                output=_pb2.JoinCallResponse,
            ),
            headers=headers,
        )

    def get_call_token(self, request: _pb2.GetCallTokenRequest, *, headers: dict[str, str] | None = None) -> _pb2.GetCallTokenResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCallToken",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.GetCallTokenRequest,
                output=_pb2.GetCallTokenResponse,
            ),
            headers=headers,
        )

    def create_call_media_publisher_token(self, request: _pb2.CreateCallMediaPublisherTokenRequest, *, headers: dict[str, str] | None = None) -> _pb2.CreateCallMediaPublisherTokenResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateCallMediaPublisherToken",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.CreateCallMediaPublisherTokenRequest,
                output=_pb2.CreateCallMediaPublisherTokenResponse,
            ),
            headers=headers,
        )

    def leave_call(self, request: _pb2.LeaveCallRequest, *, headers: dict[str, str] | None = None) -> _pb2.LeaveCallResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="LeaveCall",
                service_name="chatto.api.v1.VoiceCallService",
                input=_pb2.LeaveCallRequest,
                output=_pb2.LeaveCallResponse,
            ),
            headers=headers,
        )
